### ISSUE TITLE
CANNOT ACQUIRE THE GAME

### ISSUE THREAD

**Issue by MartynDerg** [vitor251093/resurrection-capsule#12]
I'm sure many of you may have noticed... darkspore can no longer be bought. I do not understand why on earth you are enforcing DRM when the DRM is defunct. I cannot purchase the game on steam or origin, nor can I acquire a serial code.

Enforcing DRM of a megacorporation that has completely and efficiently wiped their game from the face of the planet is absurd. They are not making any money off of the game anymore, they refuse to take my money that I actively offer to them, why on earth would you restrict this to people who were fortunate, or unfortunate, enough to purchase the game for the short time that it was available.

**Comment by vitor251093** [comment]
The reason is simple: if we don't do our best to keep it working, the project can be just shutdown by Darkspore's publisher.

Either way, you can use Resurrection Capsule with the Beta version, still available in Steam through the direct steamapp URL. It isn't the latest version, but it's a compatible version, and that provides you a valid serial code.
